### ISSUE TITLE
trialbal won't work since addition of subledgers

### ISSUE THREAD

**Issue by harry-wright** [harry-wright/adrestia#2]
```
$ python adrestia.py database.db
<adrestia> trialbal
bank:
Traceback (most recent call last):
  File "adrestia.py", line 130, in <module>
    status = main()
  File "adrestia.py", line 17, in main
    parse_opt(sel)
  File "adrestia.py", line 31, in parse_opt
    print_trialbal()
  File "adrestia.py", line 50, in print_trialbal
    retbal,rett = calc_ledgbal(ledgname,subledg)
  File "adrestia.py", line 86, in calc_ledgbal
    c.execute("SELECT SUM(amt) FROM history WHERE ledger = '%s' AND t = 'dr' AND sub LIKE '%s'" % (ledgname,subledg))
sqlite3.OperationalError: near "bank": syntax error
```

**Comment by harry-wright** [comment]
arguments passed to calc_ledgbal must be string
